### ISSUE TITLE
Prevent extra DefineMap arguments from getting passed to a template

### ISSUE THREAD

**Issue by marshallswain** [canjs/react-view-models#3]
Currently, it's not possible to cleanly use the `...rest` spread operator with destructuring in a template because the arguments includes several `DefineMap` attributes.  The following would result in an error due to unrecognized attributes like `set`, and `serialize`.

```js
import React from 'react';
import Form from 'whatever';

export default ({onSubmit, ...rest}) => {
  return (
    <Form onSubmit={onSubmit} {...rest} />
  );
};
```

It would be nice if DefineMap-specific attributes were plucked from the attributes passed to the template.

**Comment by BigAB** [comment]
This issue should actually be solved by whatever solves this other issue
https://github.com/canjs/react-view-models/issues/5

Maybe not a duplicate, but same result
